const Sponsers = () => {
  return (
    <>
      <section className="sponser-main pb-5">
        <div className="container-fluid">
          <div className="row"></div>
        </div>
      </section>
      <section className="title-sponser py-5">
        <div className="container-fluid">
          <div className="row pb-3">
            <div className="col-sm-2 title-sponser-left">
              <h3>Previous Sponsors -</h3>
            </div>
            <div className="col-sm-10 col-xs-12">
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-one.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-two.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-three.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-four.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-five.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-six.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-seven.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-eight.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-nine.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-ten.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-eleven.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twelve.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirteen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-fourteen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-fifteen.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-sixteen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-seventeen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-eighteen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-nineteen.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twenty.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentyone.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentytwo.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentythree.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentyfour.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentyfive.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentysix.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentyseven.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentyeight.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-twentynine.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirty.png")}
                    />
                  </li>
                </ul>
              </div>
              <div className="title-sponser-sub">
                <ul>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirtyone.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirtytwo.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirtythree.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirtyfour.png")}
                    />
                  </li>
                  <li>
                    <img
                      alt=""
                      srcSet=""
                      src={require("./images/image-thirtyfive.png")}
                    />
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Sponsers;
